name = "tabit-worker"
main = "src/index.js"
compatibility_date = "2024-10-01"
account_id = "6ee22d5ec21f033141d2980b8ab065c2"

# R2 bucket for audio caching
[[r2_buckets]]
bucket_name = "tabit-audio-cache"
binding = "AUDIO_BUCKET"

# Cloudflare Container binding (beta) - uncomment after container setup
# [[container_bindings]]
# name = "YTDLP_CONTAINER"
# image = "YOUR_ACCOUNT.cloudflare.net/ytdlp-service:latest"

# Environment-specific configurations
[env.production]
name = "tabit-worker-prod"

[env.dev]
name = "tabit-worker-dev"